export const countries = [
  { code: "AF", name: "Afghanistan", flagUrl: "https://flagcdn.com/w20/af.png" },
  { code: "AL", name: "Albania", flagUrl: "https://flagcdn.com/w20/al.png" },
  { code: "DZ", name: "Algeria", flagUrl: "https://flagcdn.com/w20/dz.png" },
  { code: "AS", name: "American Samoa", flagUrl: "https://flagcdn.com/w20/as.png" },
  { code: "AD", name: "Andorra", flagUrl: "https://flagcdn.com/w20/ad.png" },
  { code: "AO", name: "Angola", flagUrl: "https://flagcdn.com/w20/ao.png" },
  { code: "AI", name: "Anguilla", flagUrl: "https://flagcdn.com/w20/ai.png" },
  { code: "AQ", name: "Antarctica", flagUrl: "https://flagcdn.com/w20/aq.png" },
  { code: "AG", name: "Antigua and Barbuda", flagUrl: "https://flagcdn.com/w20/ag.png" },
  { code: "AR", name: "Argentina", flagUrl: "https://flagcdn.com/w20/ar.png" },
  { code: "AM", name: "Armenia", flagUrl: "https://flagcdn.com/w20/am.png" },
  { code: "AW", name: "Aruba", flagUrl: "https://flagcdn.com/w20/aw.png" },
  { code: "AU", name: "Australia", flagUrl: "https://flagcdn.com/w20/au.png" },
  { code: "AT", name: "Austria", flagUrl: "https://flagcdn.com/w20/at.png" },
  { code: "AZ", name: "Azerbaijan", flagUrl: "https://flagcdn.com/w20/az.png" },
  { code: "BS", name: "Bahamas", flagUrl: "https://flagcdn.com/w20/bs.png" },
  { code: "BH", name: "Bahrain", flagUrl: "https://flagcdn.com/w20/bh.png" },
  { code: "BD", name: "Bangladesh", flagUrl: "https://flagcdn.com/w20/bd.png" },
  { code: "BB", name: "Barbados", flagUrl: "https://flagcdn.com/w20/bb.png" },
  { code: "BY", name: "Belarus", flagUrl: "https://flagcdn.com/w20/by.png" },
  { code: "BE", name: "Belgium", flagUrl: "https://flagcdn.com/w20/be.png" },
  { code: "BZ", name: "Belize", flagUrl: "https://flagcdn.com/w20/bz.png" },
  { code: "BJ", name: "Benin", flagUrl: "https://flagcdn.com/w20/bj.png" },
  { code: "BM", name: "Bermuda", flagUrl: "https://flagcdn.com/w20/bm.png" },
  { code: "BT", name: "Bhutan", flagUrl: "https://flagcdn.com/w20/bt.png" },
  { code: "BO", name: "Bolivia", flagUrl: "https://flagcdn.com/w20/bo.png" },
  { code: "BA", name: "Bosnia and Herzegovina", flagUrl: "https://flagcdn.com/w20/ba.png" },
  { code: "BW", name: "Botswana", flagUrl: "https://flagcdn.com/w20/bw.png" },
  { code: "BV", name: "Bouvet Island", flagUrl: "https://flagcdn.com/w20/bv.png" },
  { code: "BR", name: "Brazil", flagUrl: "https://flagcdn.com/w20/br.png" },
  { code: "IO", name: "British Indian Ocean Territory", flagUrl: "https://flagcdn.com/w20/io.png" },
  { code: "BN", name: "Brunei Darussalam", flagUrl: "https://flagcdn.com/w20/bn.png" },
  { code: "BG", name: "Bulgaria", flagUrl: "https://flagcdn.com/w20/bg.png" },
  { code: "BF", name: "Burkina Faso", flagUrl: "https://flagcdn.com/w20/bf.png" },
  { code: "BI", name: "Burundi", flagUrl: "https://flagcdn.com/w20/bi.png" },
  { code: "KH", name: "Cambodia", flagUrl: "https://flagcdn.com/w20/kh.png" },
  { code: "CM", name: "Cameroon", flagUrl: "https://flagcdn.com/w20/cm.png" },
  { code: "CA", name: "Canada", flagUrl: "https://flagcdn.com/w20/ca.png" },
  { code: "CV", name: "Cape Verde", flagUrl: "https://flagcdn.com/w20/cv.png" },
  { code: "KY", name: "Cayman Islands", flagUrl: "https://flagcdn.com/w20/ky.png" },
  { code: "CF", name: "Central African Republic", flagUrl: "https://flagcdn.com/w20/cf.png" },
  { code: "TD", name: "Chad", flagUrl: "https://flagcdn.com/w20/td.png" },
  { code: "CL", name: "Chile", flagUrl: "https://flagcdn.com/w20/cl.png" },
  { code: "CN", name: "China", flagUrl: "https://flagcdn.com/w20/cn.png" },
  { code: "CX", name: "Christmas Island", flagUrl: "https://flagcdn.com/w20/cx.png" },
  { code: "CC", name: "Cocos (Keeling) Islands", flagUrl: "https://flagcdn.com/w20/cc.png" },
  { code: "CO", name: "Colombia", flagUrl: "https://flagcdn.com/w20/co.png" },
  { code: "KM", name: "Comoros", flagUrl: "https://flagcdn.com/w20/km.png" },
  { code: "CG", name: "Congo", flagUrl: "https://flagcdn.com/w20/cg.png" },
  { code: "CD", name: "Congo, the Democratic Republic of the", flagUrl: "https://flagcdn.com/w20/cd.png" },
  { code: "CK", name: "Cook Islands", flagUrl: "https://flagcdn.com/w20/ck.png" },
  { code: "CR", name: "Costa Rica", flagUrl: "https://flagcdn.com/w20/cr.png" },
  { code: "CI", name: "Cote D'Ivoire", flagUrl: "https://flagcdn.com/w20/ci.png" },
  { code: "HR", name: "Croatia", flagUrl: "https://flagcdn.com/w20/hr.png" },
  { code: "CU", name: "Cuba", flagUrl: "https://flagcdn.com/w20/cu.png" },
  { code: "CY", name: "Cyprus", flagUrl: "https://flagcdn.com/w20/cy.png" },
  { code: "CZ", name: "Czech Republic", flagUrl: "https://flagcdn.com/w20/cz.png" },
  { code: "DK", name: "Denmark", flagUrl: "https://flagcdn.com/w20/dk.png" },
  { code: "DJ", name: "Djibouti", flagUrl: "https://flagcdn.com/w20/dj.png" },
  { code: "DM", name: "Dominica", flagUrl: "https://flagcdn.com/w20/dm.png" },
  { code: "DO", name: "Dominican Republic", flagUrl: "https://flagcdn.com/w20/do.png" },
  { code: "EC", name: "Ecuador", flagUrl: "https://flagcdn.com/w20/ec.png" },
  { code: "EG", name: "Egypt", flagUrl: "https://flagcdn.com/w20/eg.png" },
  { code: "SV", name: "El Salvador", flagUrl: "https://flagcdn.com/w20/sv.png" },
  { code: "GQ", name: "Equatorial Guinea", flagUrl: "https://flagcdn.com/w20/gq.png" },
  { code: "ER", name: "Eritrea", flagUrl: "https://flagcdn.com/w20/er.png" },
  { code: "EE", name: "Estonia", flagUrl: "https://flagcdn.com/w20/ee.png" },
  { code: "ET", name: "Ethiopia", flagUrl: "https://flagcdn.com/w20/et.png" },
  { code: "FK", name: "Falkland Islands (Malvinas)", flagUrl: "https://flagcdn.com/w20/fk.png" },
  { code: "FO", name: "Faroe Islands", flagUrl: "https://flagcdn.com/w20/fo.png" },
  { code: "FJ", name: "Fiji", flagUrl: "https://flagcdn.com/w20/fj.png" },
  { code: "FI", name: "Finland", flagUrl: "https://flagcdn.com/w20/fi.png" },
  { code: "FR", name: "France", flagUrl: "https://flagcdn.com/w20/fr.png" },
  { code: "GF", name: "French Guiana", flagUrl: "https://flagcdn.com/w20/gf.png" },
  { code: "PF", name: "French Polynesia", flagUrl: "https://flagcdn.com/w20/pf.png" },
  { code: "TF", name: "French Southern Territories", flagUrl: "https://flagcdn.com/w20/tf.png" },
  { code: "GA", name: "Gabon", flagUrl: "https://flagcdn.com/w20/ga.png" },
  { code: "GM", name: "Gambia", flagUrl: "https://flagcdn.com/w20/gm.png" },
  { code: "GE", name: "Georgia", flagUrl: "https://flagcdn.com/w20/ge.png" },
  { code: "DE", name: "Germany", flagUrl: "https://flagcdn.com/w20/de.png" },
  { code: "GH", name: "Ghana", flagUrl: "https://flagcdn.com/w20/gh.png" },
  { code: "GI", name: "Gibraltar", flagUrl: "https://flagcdn.com/w20/gi.png" },
  { code: "GR", name: "Greece", flagUrl: "https://flagcdn.com/w20/gr.png" },
  { code: "GL", name: "Greenland", flagUrl: "https://flagcdn.com/w20/gl.png" },
  { code: "GD", name: "Grenada", flagUrl: "https://flagcdn.com/w20/gd.png" },
  { code: "GP", name: "Guadeloupe", flagUrl: "https://flagcdn.com/w20/gp.png" },
  { code: "GU", name: "Guam", flagUrl: "https://flagcdn.com/w20/gu.png" },
  { code: "GT", name: "Guatemala", flagUrl: "https://flagcdn.com/w20/gt.png" },
  { code: "GN", name: "Guinea", flagUrl: "https://flagcdn.com/w20/gn.png" },
  { code: "GW", name: "Guinea-Bissau", flagUrl: "https://flagcdn.com/w20/gw.png" },
  { code: "GY", name: "Guyana", flagUrl: "https://flagcdn.com/w20/gy.png" },
  { code: "HT", name: "Haiti", flagUrl: "https://flagcdn.com/w20/ht.png" },
  { code: "HM", name: "Heard Island and Mcdonald Islands", flagUrl: "https://flagcdn.com/w20/hm.png" },
  { code: "VA", name: "Holy See (Vatican City State)", flagUrl: "https://flagcdn.com/w20/va.png" },
  { code: "HN", name: "Honduras", flagUrl: "https://flagcdn.com/w20/hn.png" },
  { code: "HK", name: "Hong Kong", flagUrl: "https://flagcdn.com/w20/hk.png" },
  { code: "HU", name: "Hungary", flagUrl: "https://flagcdn.com/w20/hu.png" },
  { code: "IS", name: "Iceland", flagUrl: "https://flagcdn.com/w20/is.png" },
  { code: "IN", name: "India", flagUrl: "https://flagcdn.com/w20/in.png" },
  { code: "ID", name: "Indonesia", flagUrl: "https://flagcdn.com/w20/id.png" },
  { code: "IR", name: "Iran, Islamic Republic of", flagUrl: "https://flagcdn.com/w20/ir.png" },
  { code: "IQ", name: "Iraq", flagUrl: "https://flagcdn.com/w20/iq.png" },
  { code: "IE", name: "Ireland", flagUrl: "https://flagcdn.com/w20/ie.png" },
  { code: "IL", name: "Israel", flagUrl: "https://flagcdn.com/w20/il.png" },
  { code: "IT", name: "Italy", flagUrl: "https://flagcdn.com/w20/it.png" },
  { code: "JM", name: "Jamaica", flagUrl: "https://flagcdn.com/w20/jm.png" },
  { code: "JP", name: "Japan", flagUrl: "https://flagcdn.com/w20/jp.png" },
  { code: "JO", name: "Jordan", flagUrl: "https://flagcdn.com/w20/jo.png" },
  { code: "KZ", name: "Kazakhstan", flagUrl: "https://flagcdn.com/w20/kz.png" },
  { code: "KE", name: "Kenya", flagUrl: "https://flagcdn.com/w20/ke.png" },
  { code: "KI", name: "Kiribati", flagUrl: "https://flagcdn.com/w20/ki.png" },
  { code: "KP", name: "Korea, Democratic People's Republic of", flagUrl: "https://flagcdn.com/w20/kp.png" },
  { code: "KR", name: "Korea, Republic of", flagUrl: "https://flagcdn.com/w20/kr.png" },
  { code: "KW", name: "Kuwait", flagUrl: "https://flagcdn.com/w20/kw.png" },
  { code: "KG", name: "Kyrgyzstan", flagUrl: "https://flagcdn.com/w20/kg.png" },
  { code: "LA", name: "Lao People's Democratic Republic", flagUrl: "https://flagcdn.com/w20/la.png" },
  { code: "LV", name: "Latvia", flagUrl: "https://flagcdn.com/w20/lv.png" },
  { code: "LB", name: "Lebanon", flagUrl: "https://flagcdn.com/w20/lb.png" },
  { code: "LS", name: "Lesotho", flagUrl: "https://flagcdn.com/w20/ls.png" },
  { code: "LR", name: "Liberia", flagUrl: "https://flagcdn.com/w20/lr.png" },
  { code: "LY", name: "Libyan Arab Jamahiriya", flagUrl: "https://flagcdn.com/w20/ly.png" },
  { code: "LI", name: "Liechtenstein", flagUrl: "https://flagcdn.com/w20/li.png" },
  { code: "LT", name: "Lithuania", flagUrl: "https://flagcdn.com/w20/lt.png" },
  { code: "LU", name: "Luxembourg", flagUrl: "https://flagcdn.com/w20/lu.png" },
  { code: "MO", name: "Macao", flagUrl: "https://flagcdn.com/w20/mo.png" },
  { code: "MK", name: "Macedonia, the Former Yugoslav Republic of", flagUrl: "https://flagcdn.com/w20/mk.png" },
  { code: "MG", name: "Madagascar", flagUrl: "https://flagcdn.com/w20/mg.png" },
  { code: "MW", name: "Malawi", flagUrl: "https://flagcdn.com/w20/mw.png" },
  { code: "MY", name: "Malaysia", flagUrl: "https://flagcdn.com/w20/my.png" },
  { code: "MV", name: "Maldives", flagUrl: "https://flagcdn.com/w20/mv.png" },
  { code: "ML", name: "Mali", flagUrl: "https://flagcdn.com/w20/ml.png" },
  { code: "MT", name: "Malta", flagUrl: "https://flagcdn.com/w20/mt.png" },
  { code: "MH", name: "Marshall Islands", flagUrl: "https://flagcdn.com/w20/mh.png" },
  { code: "MQ", name: "Martinique", flagUrl: "https://flagcdn.com/w20/mq.png" },
  { code: "MR", name: "Mauritania", flagUrl: "https://flagcdn.com/w20/mr.png" },
  { code: "MU", name: "Mauritius", flagUrl: "https://flagcdn.com/w20/mu.png" },
  { code: "YT", name: "Mayotte", flagUrl: "https://flagcdn.com/w20/yt.png" },
  { code: "MX", name: "Mexico", flagUrl: "https://flagcdn.com/w20/mx.png" },
  { code: "FM", name: "Micronesia, Federated States of", flagUrl: "https://flagcdn.com/w20/fm.png" },
  { code: "MD", name: "Moldova, Republic of", flagUrl: "https://flagcdn.com/w20/md.png" },
  { code: "MC", name: "Monaco", flagUrl: "https://flagcdn.com/w20/mc.png" },
  { code: "MN", name: "Mongolia", flagUrl: "https://flagcdn.com/w20/mn.png" },
  { code: "MS", name: "Montserrat", flagUrl: "https://flagcdn.com/w20/ms.png" },
  { code: "MA", name: "Morocco", flagUrl: "https://flagcdn.com/w20/ma.png" },
  { code: "MZ", name: "Mozambique", flagUrl: "https://flagcdn.com/w20/mz.png" },
  { code: "MM", name: "Myanmar", flagUrl: "https://flagcdn.com/w20/mm.png" },
  { code: "NA", name: "Namibia", flagUrl: "https://flagcdn.com/w20/na.png" },
  { code: "NR", name: "Nauru", flagUrl: "https://flagcdn.com/w20/nr.png" },
  { code: "NP", name: "Nepal", flagUrl: "https://flagcdn.com/w20/np.png" },
  { code: "NL", name: "Netherlands", flagUrl: "https://flagcdn.com/w20/nl.png" },
  { code: "NC", name: "New Caledonia", flagUrl: "https://flagcdn.com/w20/nc.png" },
  { code: "NZ", name: "New Zealand", flagUrl: "https://flagcdn.com/w20/nz.png" },
  { code: "NI", name: "Nicaragua", flagUrl: "https://flagcdn.com/w20/ni.png" },
  { code: "NE", name: "Niger", flagUrl: "https://flagcdn.com/w20/ne.png" },
  { code: "NG", name: "Nigeria", flagUrl: "https://flagcdn.com/w20/ng.png" },
  { code: "NU", name: "Niue", flagUrl: "https://flagcdn.com/w20/nu.png" },
  { code: "NF", name: "Norfolk Island", flagUrl: "https://flagcdn.com/w20/nf.png" },
  { code: "MP", name: "Northern Mariana Islands", flagUrl: "https://flagcdn.com/w20/mp.png" },
  { code: "NO", name: "Norway", flagUrl: "https://flagcdn.com/w20/no.png" },
  { code: "OM", name: "Oman", flagUrl: "https://flagcdn.com/w20/om.png" },
  { code: "PK", name: "Pakistan", flagUrl: "https://flagcdn.com/w20/pk.png" },
  { code: "PW", name: "Palau", flagUrl: "https://flagcdn.com/w20/pw.png" },
  { code: "PS", name: "Palestinian Territory, Occupied", flagUrl: "https://flagcdn.com/w20/ps.png" },
  { code: "PA", name: "Panama", flagUrl: "https://flagcdn.com/w20/pa.png" },
  { code: "PG", name: "Papua New Guinea", flagUrl: "https://flagcdn.com/w20/pg.png" },
  { code: "PY", name: "Paraguay", flagUrl: "https://flagcdn.com/w20/py.png" },
  { code: "PE", name: "Peru", flagUrl: "https://flagcdn.com/w20/pe.png" },
  { code: "PH", name: "Philippines", flagUrl: "https://flagcdn.com/w20/ph.png" },
  { code: "PN", name: "Pitcairn", flagUrl: "https://flagcdn.com/w20/pn.png" },
  { code: "PL", name: "Poland", flagUrl: "https://flagcdn.com/w20/pl.png" },
  { code: "PT", name: "Portugal", flagUrl: "https://flagcdn.com/w20/pt.png" },
  { code: "PR", name: "Puerto Rico", flagUrl: "https://flagcdn.com/w20/pr.png" },
  { code: "QA", name: "Qatar", flagUrl: "https://flagcdn.com/w20/qa.png" },
  { code: "RE", name: "Reunion", flagUrl: "https://flagcdn.com/w20/re.png" },
  { code: "RO", name: "Romania", flagUrl: "https://flagcdn.com/w20/ro.png" },
  { code: "RU", name: "Russian Federation", flagUrl: "https://flagcdn.com/w20/ru.png" },
  { code: "RW", name: "Rwanda", flagUrl: "https://flagcdn.com/w20/rw.png" },
  { code: "SH", name: "Saint Helena", flagUrl: "https://flagcdn.com/w20/sh.png" },
  { code: "KN", name: "Saint Kitts and Nevis", flagUrl: "https://flagcdn.com/w20/kn.png" },
  { code: "LC", name: "Saint Lucia", flagUrl: "https://flagcdn.com/w20/lc.png" },
  { code: "PM", name: "Saint Pierre and Miquelon", flagUrl: "https://flagcdn.com/w20/pm.png" },
  { code: "VC", name: "Saint Vincent and the Grenadines", flagUrl: "https://flagcdn.com/w20/vc.png" },
  { code: "WS", name: "Samoa", flagUrl: "https://flagcdn.com/w20/ws.png" },
  { code: "SM", name: "San Marino", flagUrl: "https://flagcdn.com/w20/sm.png" },
  { code: "ST", name: "Sao Tome and Principe", flagUrl: "https://flagcdn.com/w20/st.png" },
  { code: "SA", name: "Saudi Arabia", flagUrl: "https://flagcdn.com/w20/sa.png" },
  { code: "SN", name: "Senegal", flagUrl: "https://flagcdn.com/w20/sn.png" },
  { code: "SC", name: "Seychelles", flagUrl: "https://flagcdn.com/w20/sc.png" },
  { code: "SL", name: "Sierra Leone", flagUrl: "https://flagcdn.com/w20/sl.png" },
  { code: "SG", name: "Singapore", flagUrl: "https://flagcdn.com/w20/sg.png" },
  { code: "SK", name: "Slovakia", flagUrl: "https://flagcdn.com/w20/sk.png" },
  { code: "SI", name: "Slovenia", flagUrl: "https://flagcdn.com/w20/si.png" },
  { code: "SB", name: "Solomon Islands", flagUrl: "https://flagcdn.com/w20/sb.png" },
  { code: "SO", name: "Somalia", flagUrl: "https://flagcdn.com/w20/so.png" },
  { code: "ZA", name: "South Africa", flagUrl: "https://flagcdn.com/w20/za.png" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", flagUrl: "https://flagcdn.com/w20/gs.png" },
  { code: "ES", name: "Spain", flagUrl: "https://flagcdn.com/w20/es.png" },
  { code: "LK", name: "Sri Lanka", flagUrl: "https://flagcdn.com/w20/lk.png" },
  { code: "SD", name: "Sudan", flagUrl: "https://flagcdn.com/w20/sd.png" },
  { code: "SR", name: "Suriname", flagUrl: "https://flagcdn.com/w20/sr.png" },
  { code: "SJ", name: "Svalbard and Jan Mayen", flagUrl: "https://flagcdn.com/w20/sj.png" },
  { code: "SZ", name: "Swaziland", flagUrl: "https://flagcdn.com/w20/sz.png" },
  { code: "SE", name: "Sweden", flagUrl: "https://flagcdn.com/w20/se.png" },
  { code: "CH", name: "Switzerland", flagUrl: "https://flagcdn.com/w20/ch.png" },
  { code: "SY", name: "Syrian Arab Republic", flagUrl: "https://flagcdn.com/w20/sy.png" },
  { code: "TW", name: "Taiwan", flagUrl: "https://flagcdn.com/w20/tw.png" },
  { code: "TJ", name: "Tajikistan", flagUrl: "https://flagcdn.com/w20/tj.png" },
  { code: "TZ", name: "Tanzania, United Republic of", flagUrl: "https://flagcdn.com/w20/tz.png" },
  { code: "TH", name: "Thailand", flagUrl: "https://flagcdn.com/w20/th.png" },
  { code: "TL", name: "Timor-Leste", flagUrl: "https://flagcdn.com/w20/tl.png" },
  { code: "TG", name: "Togo", flagUrl: "https://flagcdn.com/w20/tg.png" },
  { code: "TK", name: "Tokelau", flagUrl: "https://flagcdn.com/w20/tk.png" },
  { code: "TO", name: "Tonga", flagUrl: "https://flagcdn.com/w20/to.png" },
  { code: "TT", name: "Trinidad and Tobago", flagUrl: "https://flagcdn.com/w20/tt.png" },
  { code: "TN", name: "Tunisia", flagUrl: "https://flagcdn.com/w20/tn.png" },
  { code: "TR", name: "Turkey", flagUrl: "https://flagcdn.com/w20/tr.png" },
  { code: "TM", name: "Turkmenistan", flagUrl: "https://flagcdn.com/w20/tm.png" },
  { code: "TC", name: "Turks and Caicos Islands", flagUrl: "https://flagcdn.com/w20/tc.png" },
  { code: "TV", name: "Tuvalu", flagUrl: "https://flagcdn.com/w20/tv.png" },
  { code: "UG", name: "Uganda", flagUrl: "https://flagcdn.com/w20/ug.png" },
  { code: "UA", name: "Ukraine", flagUrl: "https://flagcdn.com/w20/ua.png" },
  { code: "AE", name: "United Arab Emirates", flagUrl: "https://flagcdn.com/w20/ae.png" },
  { code: "GB", name: "United Kingdom", flagUrl: "https://flagcdn.com/w20/gb.png" },
  { code: "US", name: "United States", flagUrl: "https://flagcdn.com/w20/us.png" },
  { code: "UM", name: "United States Minor Outlying Islands", flagUrl: "https://flagcdn.com/w20/um.png" },
  { code: "UY", name: "Uruguay", flagUrl: "https://flagcdn.com/w20/uy.png" },
  { code: "UZ", name: "Uzbekistan", flagUrl: "https://flagcdn.com/w20/uz.png" },
  { code: "VU", name: "Vanuatu", flagUrl: "https://flagcdn.com/w20/vu.png" },
  { code: "VE", name: "Venezuela", flagUrl: "https://flagcdn.com/w20/ve.png" },
  { code: "VN", name: "Viet Nam", flagUrl: "https://flagcdn.com/w20/vn.png" },
  { code: "VG", name: "Virgin Islands, British", flagUrl: "https://flagcdn.com/w20/vg.png" },
  { code: "VI", name: "Virgin Islands, U.S.", flagUrl: "https://flagcdn.com/w20/vi.png" },
  { code: "WF", name: "Wallis and Futuna", flagUrl: "https://flagcdn.com/w20/wf.png" },
  { code: "EH", name: "Western Sahara", flagUrl: "https://flagcdn.com/w20/eh.png" },
  { code: "YE", name: "Yemen", flagUrl: "https://flagcdn.com/w20/ye.png" },
  { code: "ZM", name: "Zambia", flagUrl: "https://flagcdn.com/w20/zm.png" },
  { code: "ZW", name: "Zimbabwe", flagUrl: "https://flagcdn.com/w20/zw.png" }
];
