import express from 'express';
import { HttpAgent, Actor } from '@dfinity/agent';
import { Principal } from '@dfinity/principal';

const router = express.Router();

// Load canister IDL and ID from local files (generated by dfx)
let idlFactory = null;
let canisterId = null;

try {
  // Attempt to import from plugin canister build (if deployed/compiled)
  // These paths depend on your dfx setup; provide fallbacks
  const candid = await import('./canister/.dfx/local/canisters/icp_backend/icp_backend.did.js').catch(() => null);
  const ids = await import('./canister/.dfx/local/canister_ids.json', { assert: { type: 'json' } }).catch(() => null);
  idlFactory = candid?.idlFactory || null;
  canisterId = ids?.default?.icp_backend || ids?.canisters?.icp_backend || process.env.ICP_CANISTER_ID || null;
} catch {}

function getActor() {
  if (!idlFactory || !canisterId) {
    throw new Error('ICP canister not initialized. Deploy canister or set ICP_CANISTER_ID.');
  }
  const agent = new HttpAgent({ host: process.env.ICP_HOST || 'https://ic0.app' });
  return Actor.createActor(idlFactory, { agent, canisterId });
}

router.get('/health', (req, res) => {
  res.json({ success: true, plugin: 'icp', canisterConfigured: Boolean(canisterId && idlFactory) });
});

router.get('/greet', async (req, res) => {
  try {
    const actor = getActor();
    const message = await actor.greet('Olivia');
    res.json({ success: true, data: { message } });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

router.get('/stats', async (req, res) => {
  try {
    const actor = getActor();
    const userCount = await actor.getUserCount?.();
    const messageCount = await actor.getMessageCount?.();
    res.json({ success: true, data: { userCount: Number(userCount || 0), messageCount: Number(messageCount || 0) } });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

export default router;


